add todo
AnhDuy20/learn-reactjs pull request #1
Opened 2023-07-19 10:20 UTC by AnhDuy20

2023-07-19 11:35 UTC, hoanglong1202 commented
@AnhDuy20 Add overview please :hand:

2023-07-19 11:38 UTC, hoanglong1202 requested changes

2023-07-19 11:38 UTC, hoanglong1202 commented on src/compoments/Header/styles.scss
Không dùng thì up lên làm gì 👎

2023-07-19 11:38 UTC, hoanglong1202 commented on src/compoments/Loading/styles.scss
Cái này nữa 🔢

2023-07-19 15:57 UTC, AnhDuy20 commented on src/compoments/Loading/styles.scss
👍

2023-07-19 15:57 UTC, AnhDuy20 commented on src/compoments/Header/styles.scss
👍

2023-07-20 10:57 UTC, hoanglong1202 approved these changes

2023-07-20 10:57 UTC, hoanglong1202 commented
🍶

2023-07-20 11:00 UTC, merged