Feature: Add filter Todo
AnhDuy20/learn-reactjs pull request #2
Opened 2023-07-20 13:33 UTC by hoanglong1202

2023-07-20 13:35 UTC, hoanglong1202 commented on src/features/Todo/pages/index.jsx
> +  const renderedTodoList = todoList.filter(
👎 Không bao giờ dùm biến trực tiếp như vậy

2023-07-20 13:49 UTC, hohoaisan requested changes

2023-07-20 13:49 UTC, hohoaisan commented on src/features/Todo/pages/index.jsx
> +  const renderedTodoList = todoList.filter(
@AnhDuy20 đưa ra 1 object chứa mấy cái hằng này là code dễ đọc hơn

2023-08-02 16:24 UTC, hohoaisan approved these changes
LGTM!

2023-08-02 16:26 UTC, hoanglong1202 commented
Merged now 🙄

2023-08-02 16:27 UTC, merged